--CREAR BASE DE DATOS
CREATE DATABASE EMPLEADO
--HACIENDO MODIFICACIONES 
USE EMPLEADO
--creat tablas
CREATE TABLE Tbl_empleado (
Id_empleado INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Empl_nombre VARCHAR(40) NOT NULL,
Empl_apellido VARCHAR(40) NOT NULL,
Empl_DUI INT,
Empl_direccion VARCHAR(50),
Empl_tel INT,
Empl_email VARCHAR(80) NOT NULL,
Empl_cargo VARCHAR(40) NOT NULL,
);